name: Build and Push Docker Image

on:
  push:
    branches:
      - main  # or your deployment branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:   
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
    
      - name: Build with Maven
        run: mvn clean package --no-transfer-progress

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: jordanurbaezlu/next-pokedex-java-backend:latest
          platforms: linux/amd64
      
      - name: Trigger Render Deploy
        run: |
            curl -X POST "${{ secrets.RENDER_DEPLOY_HOOK_URL }}"
